[APP-2955] Add custom ENV_VAR as Runtime Params
datarobot/dr-apps pull request #54
Opened 2024-07-25 18:11 UTC by amoddhopavkar2

- JIRA Ticket: [APP-2955](https://datarobot.atlassian.net/jira/software/c/projects/APP/boards/1054?selectedIssue=APP-2955)

2024-08-30 16:06 UTC, amoddhopavkar2 commented
## Demo:

https://github.com/user-attachments/assets/b30aa2aa-2c5b-40d3-b44b-b24bcc1e26aa

2024-09-02 09:27 UTC, kideh88 approved these changes
One question but otherwise I think its good :+1:  
Would like to request another review from @ben-cutler-datarobot or @demchukilya to make sure :eyes:

2024-09-02 09:27 UTC, kideh88 commented on tests/cli/test_create.py
> -        match=[auth_matcher, source_version_update_data_matcher],
What makes this matcher no longer necessary?

2024-09-02 09:38 UTC, demchukilya commented on drapps/helpers/custom_app_sources_functions.py
> +
I think it's better to do as part of main payload instead of separate argument in second request.

2024-09-02 09:52 UTC, demchukilya requested changes
Looks functional, but It's better to fix places noted by me.

Additionally we can have a warning for cases when user try to use runtime parameters with uploading docker image.

2024-09-02 09:52 UTC, demchukilya commented on drapps/create.py
> +        if relative_path.lower() == 'metadata.yaml':
I think we don't need here `lower` because on backend in DR we do not use it.

2024-09-02 09:52 UTC, demchukilya commented on drapps/create.py
> +                valid_runtime_params,
In such form, if we have more than 50 files, with each group of files we will have additional request with the same runtime params.

2024-09-05 12:08 UTC, demchukilya approved these changes

2024-09-05 14:19 UTC, merged